services:
  mysql:
    image: 'mysql:8.0'
    container_name: my_graduation_db
    restart: always
    environment:
      - 'MYSQL_DATABASE=recruitment_db'
      - 'MYSQL_ROOT_PASSWORD=123456'
    ports:
      - '3307:3306' 
    volumes:
      - ./mysql-data:/var/lib/mysql 